### ISSUE TITLE
Periodic cleanup of files used/created by PuNDIT agents

### ISSUE THREAD

**Issue by dannylhy** [pundit-project/pundit#13]
There are 2 cases where the PuNDIT subsystem creates files:
- The PuNDIT archiver to agent interface currently stores tests as JSON files 
- There is the option to save problematic timeseries, which writes test results where a problem occurred to a specific directory

Both need to be limited by age or total size so we don't end up clogging up the disk on the agent machine

**Comment by gcarcassi** [comment]
No longer applies
